CREATE TABLE  grocery
(
id INTEGER PRIMARY KEY AUTOINCREMENT,
name TEXT NOT NULL,
upc TEXT NOT NULL
);
CREATE TABLE inventory
(
id INTEGER PRIMARY KEY AUTOINCREMENT,
grocery_id INTEGER NOT NULL,
quantity UNSIGNED INTEGER NOT NULL,
date_purchased DATE DEFAULT CURRENT_TIMESTAMP,
FOREIGN KEY(grocery_id) REFERENCES grocery(id),
FOREIGN KEY(user_id) REFERENCES user(id)
);